version: '3.8'

services:
  backend:
    image: ghcr.io/jjun522/oculus_color_test/backend:latest
    ports:
      - "8000:8000"
      - "50002:50002/udp"
    restart: always

  frontend:
    image: ghcr.io/jjun522/oculus_color_test/frontend:latest
    ports:
      - "12346:80"
    restart: always
